AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Testing cloudformation for IBD
Parameters:
  s3Bucket:
    Type: String
  DynamoDbTable:
    Type: String
Resources:
  PdfToJson:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      Handler: index.handler
      MemorySize: 768
      Runtime: python3.8
      Timeout: 300
      Tracing: Active
      CodeUri: s3://ibdcentreb3cbdd9c0c2a495498c88bf5c73a4aeadevu-devu/229c82469c86e69af9476979b3b974a6
      Policies:
      - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      - arn:aws:iam::aws:policy/ComprehendMedicalFullAccess
      - TextractPolicy: {}
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDbTable
      - S3CrudPolicy:
          BucketName:
            Ref: s3Bucket
      Environment:
        Variables:
          BUCKET_NAME:
            Ref: s3Bucket
          DYNAMO_TABLE_NAME:
            Ref: DynamoDbTable
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
        - PdfToJson
        - Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount:
        Ref: AWS::AccountId
      SourceArn:
        Fn::Sub: arn:aws:s3:::${s3Bucket}
  lambdaParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub: /ibd/lambdaArn
      Type: String
      Value:
        Fn::GetAtt:
        - PdfToJson
        - Arn
      Description:
        Fn::Sub: LambdaArn for ibd centre
Outputs:
  PdfToJsonArn:
    Value:
      Fn::GetAtt:
      - PdfToJson
      - Arn
