version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ibd-sam-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cenpt968dvxb"
s3_prefix = "ibd-sam-test"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = "s3Bucket=\"ibdcentreb3cbdd9c0c2a495498c88bf5c73a4aea225227-devp\" DynamoDbTable=\"Status-oxoavb4owvgxroib2b44eqkjdm-devp\""
