AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Testing cloudformation for IBD
Parameters:
  s3Bucket:
    Type: String
  DynamoDbTable:
    Type: String

Globals:
  Function:
    AutoPublishAlias: live
    Handler: index.handler
    MemorySize: 768
    Runtime: python3.8
    Timeout: 300
    Tracing: Active
    
Resources:
  PdfToJson:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./backend
      Policies:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/ComprehendMedicalFullAccess
        - TextractPolicy: {}
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDbTable
        - S3CrudPolicy:
            BucketName: !Ref s3Bucket
      Environment:
        Variables:
          BUCKET_NAME: !Ref s3Bucket
          DYNAMO_TABLE_NAME: !Ref DynamoDbTable
    Events:
      S3Event:
        Type: S3
        Properties:
          Bucket:
            Ref: s3Bucket     # This must be the name of an S3 bucket declared in the same template file
          Events: s3:ObjectCreated:*
          Filter:
            S3Key:
              Rules:
              - Name: suffix    # or "suffix"
                Value: .json      # The value to search for in the S3 object key names

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt PdfToJson.Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub 'arn:aws:s3:::${s3Bucket}' 

Outputs:
  PdfToJsonArn:
      Value: !GetAtt PdfToJson.Arn
