AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Testing cloudformation for IBD

Parameters:
  s3Bucket:
    Type: String
  DynamoDbTable:
    Type: String

Resources:
  PdfToJson:
    Type: AWS::Serverless::Function 
    Properties:
      AutoPublishAlias: live
      Handler: index.handler
      MemorySize: 768
      Runtime: python3.8
      Timeout: 300
      Tracing: Active
      CodeUri: ./backend
      Policies:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/ComprehendMedicalFullAccess
        - TextractPolicy: {}
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDbTable
        - S3CrudPolicy:
            BucketName: !Ref s3Bucket
      Environment:
        Variables:
          BUCKET_NAME: !Ref s3Bucket
          DYNAMO_TABLE_NAME: !Ref DynamoDbTable

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt PdfToJson.Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub 'arn:aws:s3:::${s3Bucket}' 

  lambdaParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        !Sub /ibd/lambdaArn
      Type: String
      Value:
        !GetAtt PdfToJson.Arn
      Description: !Sub LambdaArn for ibd centre

Outputs:
  PdfToJsonArn:
      Value: !GetAtt PdfToJson.Arn
