/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:772ddc37-7614-413b-a7a7-a8389e320cd0",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_DqL1zruS5",
    "aws_user_pools_web_client_id": "44vp1i0c3mbilsqafnsfem0iva",
    "oauth": {},
    "aws_user_files_s3_bucket": "ibdcentreb3cbdd9c0c2a495498c88bf5c73a4aea221621-dev",
    "aws_user_files_s3_bucket_region": "ca-central-1",
    "aws_appsync_graphqlEndpoint": "https://4dctb7zw75c7zptpb3ftoegpma.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
